language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  allow_failures:
    - php: 7
    - php: hhvm

before_script:
  - composer self-update
  - composer install

script:
  - phpunit --coverage-text

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == "5.4" ]]; then php vendor/bin/coveralls -v; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "5.5" ]]; then php vendor/bin/coveralls -v; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]]; then php vendor/bin/coveralls -v; fi
